export const options = [
  { value: "web-development", label: "Веб-разработка" },
  { value: "game-development", label: "Разработка игр" },
  { value: "mobile-development", label: "Мобильная разработка" },
  { value: "desktop-development", label: "Десктоп-разработка" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "cpp", label: "C++" },
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "unity", label: "Unity" },
  { value: "unreal-engine", label: "Unreal Engine" },
  { value: "ai", label: "Искусственный интеллект" },
  { value: "machine-learning", label: "Машинное обучение" },
  { value: "data-science", label: "Data Science" },
  { value: "cybersecurity", label: "Кибербезопасность" },
  { value: "ui-ux", label: "UI/UX дизайн" },
  { value: "3d-modeling", label: "3D-моделирование" },
  { value: "arduino", label: "Arduino / IoT" },
  { value: "robotics", label: "Робототехника" },
  { value: "hackathons", label: "Хакатоны" },
  { value: "blockchain", label: "Блокчейн" },
  { value: "devops", label: "DevOps" },
  { value: "open-source", label: "Open Source" },
  { value: "sat-preparation", label: "Подготовка к SAT" },
  { value: "ielts-toefl-preparation", label: "Подготовка к IELTS / TOEFL" },
  { value: "math", label: "Математика" },
  { value: "physics", label: "Физика" },
  { value: "chemistry", label: "Химия" },
  { value: "biology", label: "Биология" },
  { value: "history", label: "История" },
  { value: "geography", label: "География" },
  { value: "english", label: "Английский язык" },
  { value: "german", label: "Немецкий язык" },
  { value: "turkish", label: "Турецкий язык" },
  { value: "reading", label: "Чтение книг" },
  { value: "academic-writing", label: "Академическое письмо" },
  { value: "debates", label: "Дебаты" },
  { value: "public-speaking", label: "Публичные выступления" },
  { value: "speed-reading", label: "Скорочтение" },
  { value: "time-management", label: "Тайм-менеджмент" },
  { value: "self-development", label: "Саморазвитие" },
  { value: "leadership", label: "Лидерство" },
  { value: "emotional-intelligence", label: "Эмоциональный интеллект" },
  { value: "entrepreneurship", label: "Предпринимательство" },
  { value: "financial-literacy", label: "Финансовая грамотность" },
  { value: "startups", label: "Стартапы" },
  { value: "sales", label: "Продажи" },
  { value: "marketing", label: "Маркетинг" },
  { value: "copywriting", label: "Копирайтинг" },
  { value: "social-media", label: "Продвижение в соцсетях" },
  { value: "branding", label: "Брендинг" },
  { value: "project-management", label: "Проджект-менеджмент" },
  { value: "data-analysis", label: "Анализ данных" },
  { value: "excel-google-sheets", label: "Excel и Google Таблицы" },
  { value: "soft-skills", label: "Soft Skills" },
  { value: "networking", label: "Нетворкинг" },
  { value: "career-planning", label: "Карьерное планирование" },
  { value: "resume-interviews", label: "Резюме и собеседования" },
  { value: "graphic-design", label: "Графический дизайн" },
  { value: "illustration", label: "Иллюстрация" },
  { value: "animation", label: "Анимация" },
  { value: "video-editing", label: "Видеомонтаж" },
  { value: "photography", label: "Фотография" },
  { value: "music", label: "Музыка" },
  { value: "singing", label: "Пение" },
  { value: "guitar", label: "Игра на гитаре" },
  { value: "piano", label: "Игра на фортепиано" },
  { value: "drawing", label: "Рисование" },
  { value: "dance", label: "Танцы" },
  { value: "theater", label: "Театр" },
  { value: "cinema", label: "Кино" },
  { value: "writing", label: "Писательство" },
  { value: "comics", label: "Комиксы" },
  { value: "architecture", label: "Архитектура" },
  { value: "fashion-style", label: "Мода и стиль" },
  { value: "football", label: "Футбол" },
  { value: "basketball", label: "Баскетбол" },
  { value: "volleyball", label: "Волейбол" },
  { value: "boxing", label: "Бокс" },
  { value: "taekwondo", label: "Тхэквондо" },
  { value: "swimming", label: "Плавание" },
  { value: "skiing", label: "Лыжи / Сноуборд" },
  { value: "tennis", label: "Теннис" },
  { value: "running", label: "Бег" },
  { value: "gym", label: "Тренировки в зале" },
  { value: "yoga", label: "Йога" },
  { value: "meditation", label: "Медитация" },
  { value: "tourism", label: "Туризм" },
  { value: "mountaineering", label: "Альпинизм" },
  { value: "camping", label: "Кемпинг" },
  { value: "cycling", label: "Велоспорт" },
  { value: "skateboarding", label: "Скейтбординг" },
  { value: "volunteering", label: "Волонтёрство" },
  { value: "eco-activism", label: "Эко-активизм" },
  { value: "animal-rights", label: "Защита прав животных" },
  { value: "inclusion", label: "Инклюзия и равноправие" },
  { value: "social-projects", label: "Социальные проекты" },
  { value: "charity", label: "Благотворительность" },
  { value: "education-for-all", label: "Образование для всех" },
  { value: "mental-health", label: "Поддержка ментального здоровья" },
  { value: "civic-engagement", label: "Гражданская активность" },
  { value: "youth-work", label: "Работа с молодежью" },
  { value: "video-games", label: "Видеоигры" },
  { value: "board-games", label: "Настольные игры" },
  { value: "anime", label: "Аниме" },
  { value: "manga", label: "Манга" },
  { value: "internet-surfing", label: "Серфинг в интернете" },
  { value: "movies", label: "Просмотр фильмов" },
  { value: "travel", label: "Путешествия" },
  { value: "cooking", label: "Кулинария" },
  { value: "memes", label: "Мемы" },
  { value: "blogs-youtube", label: "Блоги и YouTube" },
  { value: "space", label: "Космос и вселенная" },
];
export const optionsOrg = [
  { value: "internship-placement", label: "Размещение стажировок" },
  { value: "volunteer-search", label: "Поиск волонтёров" },
  {
    value: "course-promotion",
    label: "Продвижение курсов / образовательных программ",
  },
];
